FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml .
RUN pip install --no-cache-dir -e .
COPY ui ui
ENV API_URL=http://localhost:8001
EXPOSE 8501
CMD ["streamlit", "run", "ui/App.py", "--server.port=8501", "--server.address=0.0.0.0"]
