name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: pip install -e .[dev]
      - name: Lint
        run: ruff check . && black --check . && isort --check-only .
      - name: Tests
        run: pytest -q --maxfail=1 --disable-warnings
